NumPy - Numerical Python

Advantages of Numpy arrays:

    1. Allows several Mathmatical Operation
    2. Faster operation

List vs Numpy - Time Taken

In [301]:
import numpy as np
from time import process_time

# time taken by a list
python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.0


In [302]:
import numpy as np
from time import process_time

np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5 # np_array = np_array + 5
end_time = process_time()
print(end_time - start_time)

0.0


# Numpy Arrays

In [303]:
list1 = [1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [304]:
np_array = np.array([1,2,3,4,5])
print(np_array)
print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [305]:
# creating a one dimention array
a = np.array([1,2,3,4])
print(a)
a.shape

[1 2 3 4]


(4,)

In [306]:
# two dimentional array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [307]:
c = np.array([(1,2,3),(4,5,6)],dtype=float)
print(c)

[[1. 2. 3.]
 [4. 5. 6.]]


# Initial Placeholder in numpy arrays

In [308]:
# create a numpy of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [309]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [310]:
# create an array of particular value
a = np.full((5,4),5)
print(a)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [311]:
# create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [312]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.68998942 0.89670163 0.36742491 0.66979952]
 [0.49817313 0.78811924 0.97089092 0.44495076]
 [0.9986776  0.77054897 0.41297193 0.27141255]]


In [313]:
# random values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[81 78 65 20 76]
 [65 28 47 58 22]
 [67 31 82 23 81]]


In [314]:
# array of eveniy spaced vlaue --> specifiy the number of values you want
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [315]:
# array of evenly spaced values --> specifying the stop
a = np.arange(10,30,5)
print(a)

[10 15 20 25]


In [316]:
# convert a list to an array
list1 = [10,20,30,40]
np_array = np.array(list1)
print(np_array)
print(type)

[10 20 30 40]
<class 'type'>


# Analysing a numpy array

In [317]:
c = np.random.randint(10,90,(5,5))
print(c)

[[83 56 59 51 20]
 [42 46 16 69 89]
 [41 32 40 68 73]
 [18 66 57 26 28]
 [54 10 87 44 60]]


In [318]:
# array dimention
c = np.random.randint(10,90,(5,5))
print(c.shape)

(5, 5)


In [319]:
# number of dimention
c = np.random.randint(10,90,(5,5))
print(c.ndim)

2


In [320]:
# number of element present in the array
c = np.random.randint(10,90,(5,5))
print(c.size)

25


In [321]:
# checking the data type of values in the array
c = np.random.randint(10,90,(5,5))
print(c.dtype)

int32


# Mathmatical operation on a np array

In [322]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2) # concatenate or join two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [323]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[0 6 1]
 [9 2 8]
 [8 3 4]]
[[10 11 16]
 [15 18 14]
 [10 17 13]]


In [324]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a + b)

[[20 24 20]
 [22 18 16]
 [26 15 20]]


In [325]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a-b)

[[ -2  -3 -10]
 [-16  -3 -14]
 [ -7 -11  -5]]


In [326]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a * b)

[[135  44  77]
 [ 88 136  48]
 [ 77  33  95]]


In [327]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a / b)

[[0.23076923 0.7        0.        ]
 [0.7        0.         0.06666667]
 [0.53333333 0.45454545 0.58333333]]


In [328]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(np.add(a,b))

[[20 21 15]
 [10 15 18]
 [21 21 16]]


In [329]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(np.subtract(a,b))

[[-14  -6 -15]
 [-10 -10 -13]
 [ -5  -6 -16]]


In [330]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(np.multiply(a,b))

[[ 15 133 108]
 [ 68  77  18]
 [105   0 108]]


In [331]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(np.divide(a,b))

[[0.44444444 0.42857143 0.4       ]
 [0.58333333 0.61538462 0.05263158]
 [0.31578947 0.08333333 0.41666667]]


In [332]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(np.mod(a,b))

[[7 7 1]
 [2 6 5]
 [4 2 9]]


# Array Manupulation

In [333]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[6 2 7]
 [7 8 9]]
(2, 3)


In [334]:
# transpose
array = np.random.randint(0,10,(2,3))
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[5 5]
 [7 9]
 [2 3]]
(3, 2)


In [335]:
array = np.random.randint(0,10,(2,3))
trans2 = array.T
print(trans2)
print(trans2.shape)

[[2 0]
 [3 0]
 [7 2]]
(3, 2)


In [336]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[5 6 9]
 [6 5 1]]
(2, 3)


In [337]:
a = np.random.randint(0,10,(2,3))
b = a.reshape(3,2)
print(b.shape)

(3, 2)


In [338]:
# print normal array
import numpy as np
myarr = np.array([3,6,32,7])
print(myarr)
myarr

[ 3  6 32  7]


array([ 3,  6, 32,  7])

In [339]:
# print normal array
import numpy as np
myarr = np.array([3,6,32,7])
print(myarr)
myarr

[ 3  6 32  7]


array([ 3,  6, 32,  7])

In [340]:
# print with data type
myarr = np.array([3,6,32,7],np.int8)
print(myarr)
myarr

[ 3  6 32  7]


array([ 3,  6, 32,  7], dtype=int8)

In [341]:
myarr = np.array([3,6,32,7],np.int8)
print([0,1])
print(myarr[0])
myarr

[0, 1]
3


array([ 3,  6, 32,  7], dtype=int8)

In [342]:
myarr = np.array([[3,6,32,7]],np.int8)
print(myarr[0])
print(myarr[0,1])
myarr

[ 3  6 32  7]
6


array([[ 3,  6, 32,  7]], dtype=int8)

In [343]:
# change the element
myarr = np.array([[3,6,32,7]],np.int8)
myarr[0,1] = 45
print(myarr)
myarr

[[ 3 45 32  7]]


array([[ 3, 45, 32,  7]], dtype=int8)

# Array creations: Conversion from other Python structure

In [344]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])
print(listarray)
listarray

[[1 2 3]
 [5 8 5]
 [0 3 1]]


array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [345]:
# check data dtype
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])
listarray.dtype

dtype('int32')

In [346]:
# check shape of the array
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])
listarray.shape

(3, 3)

In [347]:
# check the array element array size
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])
listarray.size

9

In [348]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [349]:
zeros = np.zeros((2,5))
zeros.dtype

dtype('float64')

In [350]:
zeros = np.zeros((2,5))
zeros.shape

(2, 5)

In [351]:
zerso = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [352]:
# it is print untill the range function
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [353]:
# it is give the value of two different parameter
lspace = np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [354]:
lspace = np.linspace(1,50,10)
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [355]:
lspace = np.linspace(1,4,4)
lspace

array([1., 2., 3., 4.])

In [356]:
lspace = np.linspace(1,5,4)
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [357]:
emp = np.empty((4,6))
emp

array([[8.19124398e-312, 7.31217156e-322, 0.00000000e+000,
        0.00000000e+000, 1.69119330e-306, 1.16095484e-028],
       [5.04533094e+223, 2.13423712e+161, 2.93494606e+222,
        1.38519249e+219, 6.96765945e+252, 4.48305975e-067],
       [2.17975725e+243, 3.74168445e+233, 6.23543081e+228,
        4.83245960e+276, 6.96770842e+252, 9.24935094e+135],
       [3.50179473e+251, 1.71872057e+161, 1.46899930e+179,
        9.08367237e+223, 1.16466228e-028, 1.03785332e-314]])

In [358]:
emp_like = np.empty_like(lspace)
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [359]:
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [360]:
ide = np.identity(45)
ide.shape

(45, 45)

In [361]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [362]:
# for multidimentional array
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [363]:
# for 1D array
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [364]:
arr.shape

(99,)

# Numpy axis

In [365]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [366]:
# all sum to x axis
x = [[1,2,3],[4,5,6],[7,1,0]]
ar.sum(axis=0)

array([12,  8,  9])

In [367]:
# all sum to y axis
x = [[1,2,3],[4,5,6],[7,1,0]]
ar.sum(axis=1)

array([ 6, 15,  8])

In [368]:
# transpose matrix
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [369]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.flat

In [370]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [371]:
# find max argument index
one = np.array([1,3,4,634,2])
one.argmax()

3

In [372]:
# find min argument index
one = np.array([1,3,4,634,2])
one.argmin()

0

In [373]:
# element er value onujay index dekhay
one = np.array([1,3,4,634,2])
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [374]:
# maximum value er index ber korar jonno
one = np.array([1,3,4,634,2])
one.argmax()

3

In [375]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [376]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [377]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [378]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [379]:
# marge all element
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [380]:
# reshape every element
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [381]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.reshape(9,)

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [382]:
# add to array from difference source
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [383]:
[324,34] + [34,546]

[324, 34, 34, 546]

In [384]:
# matrix multipication
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [385]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [386]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.max()

7

In [387]:
# find element an array
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [388]:
# count non zero element
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
np.count_nonzero(ar)

8

In [389]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [390]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar[1,2] = 0
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [391]:
import sys
py_ar = [0,4,55,2]
np_ar = np.array(py_ar)
sys.getsizeof(1) * len(py_ar)

112

In [392]:
import sys
py_ar = [0,4,55,2]
np_ar = np.array(py_ar)
np_ar.itemsize * np_ar.size

16

In [393]:
# tool list
py_ar = [0,4,55,2]
np_ar = np.array(py_ar)
np_ar.tolist()

[0, 4, 55, 2]

In [394]:
# get dimention
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b.ndim

2

# Accessing/Changing specific elements, rows, columns, etc

In [395]:
# get specific element
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x[1]

array([ 8,  9, 10, 11, 12, 13, 14])

In [396]:
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x[1,5]

13

In [397]:
# get a specific row
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [398]:
# get specific columns
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x[:,2]

array([ 3, 10])

In [399]:
# getting a little fance [start-index:end-index:steps-size]
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x[0, 1:6:2]

array([2, 4, 6])

In [400]:
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x[1,5] = 20
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [401]:
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x[:,2] = 5
print(x)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13 14]]


In [402]:
# 3d dimentional array
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [403]:
# get specific element (work outside in)
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b[0,1,1]

4

In [404]:
# get specific element (work outside in)
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [405]:
# replace
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# initilizing different types of array

In [406]:
# all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [407]:
np.zeros((4,2,2),dtype='int32')

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [408]:
# any other numbers
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [409]:
np.random.randint(7,size=(3,3))

array([[1, 2, 3],
       [5, 3, 1],
       [0, 6, 4]])

In [410]:
# indetity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [411]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [412]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [413]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# be careful when copying arrays!!

In [414]:
a = np.array([1,2,3])
b = a
b

array([1, 2, 3])

In [415]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)

[100   2   3]


In [416]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)

[100   2   3]


# Mathmematics

In [417]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [418]:
a = np.array([1,2,3,4])
a + 2

array([3, 4, 5, 6])

In [419]:
a = np.array([1,2,3,4])
a - 2

array([-1,  0,  1,  2])

In [420]:
a = np.array([1,2,3,4])
a * 2

array([2, 4, 6, 8])

In [421]:
a = np.array([1,2,3,4])
a / 2

array([0.5, 1. , 1.5, 2. ])

In [422]:
b = np.array([1,0,1,0])
a = np.array([1,2,3,4])
a + b

array([2, 2, 4, 4])

In [423]:
a = np.array([1,2,3,4])
a ** 2

array([ 1,  4,  9, 16])

In [424]:
a = np.array([1,2,3,4])
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [425]:
a = np.array([1,2,3,4])
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# linear alzebra

In [426]:
# find the determinart
c = np.identity(3)
np.linalg.det(c)

1.0

In [427]:
# reference docs ()
# determinant
# trace
# singular vector Decomoposition
# eigenvalues
# matrix norm
# inverse
# etc

# Statistics

In [428]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [429]:
stats = np.array([[1,2,3],[4,5,6]])
np.min(stats)

1

In [430]:
stats = np.array([[1,2,3],[4,5,6]])
np.max(stats)

6

In [431]:
stats = np.array([[1,2,3],[4,5,6]])
np.min(stats,axis=0)

array([1, 2, 3])

In [432]:
stats = np.array([[1,2,3],[4,5,6]])
np.max(stats,axis=0)

array([4, 5, 6])

In [433]:
stats = np.array([[1,2,3],[4,5,6]])
np.min(stats,axis=1)

array([1, 4])

In [434]:
stats = np.array([[1,2,3],[4,5,6]])
np.max(stats,axis=1)

array([3, 6])

# Reognaizing Arrays

In [435]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [436]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [437]:
# vertical stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [438]:
# horizontal stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Mesellaneous

Load Data from File

In [439]:
import numpy as np
np.genfromtxt('data.txt',delimiter=',')

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   5.,
          6.,   7.,   0.,  11.,  12.,   3.,  19.],
       [  1.,  22.,  33.,  11., 999.,  12.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [440]:
import numpy as np
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata.astype('int32')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   5.,
          6.,   7.,   0.,  11.,  12.,   3.,  19.],
       [  1.,  22.,  33.,  11., 999.,  12.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [441]:
import numpy as np
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   5,   6,   7,
          0,  11,  12,   3,  19],
       [  1,  22,  33,  11, 999,  12,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

# Boolean masking and Advanced Indexing

In [442]:
import numpy as np
before = np.genfromtxt('data.txt',delimiter=',')
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [443]:
import numpy as np
before = np.genfromtxt('data.txt',delimiter=',')
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [444]:
# you can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [445]:
import numpy as np
before = np.genfromtxt('data.txt',delimiter=',')
np.any(before>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [446]:
import numpy as np
before = np.genfromtxt('data.txt',delimiter=',')
np.any(before>50,axis=1)

array([ True,  True,  True])

In [447]:
import numpy as np
before = np.genfromtxt('data.txt',delimiter=',')
((before > 50) & (before < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [448]:
import numpy as np
before = np.genfromtxt('data.txt',delimiter=',')
(~((before > 50) & (before < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])