# Lists: ordered, mutable, allows duplicate elements

In [1]:
mylist = ["banana", "cherry", "apple"]
print(mylist)

['banana', 'cherry', 'apple']


In [2]:
# create empty list
mylist = list()
print(mylist)

[]


In [3]:
mylist = []
print(mylist)

[]


In [4]:
# list allow anything
mylist = [5,True,'apple']
print(mylist)

[5, True, 'apple']


In [5]:
# list also allow duplicate element
mylist = ['appel','apple']
print(mylist)

['appel', 'apple']


In [7]:
mylist = ['banana','cherry','apple']
list = mylist[0]
print(list)
list = mylist[-1]
print(list)

banana
apple


In [8]:
# with using for loop
mylist = ['banana','cherry','apple']
for i in mylist:
    print(i)

banana
cherry
apple


In [9]:
# with if statement
mylist = ['banana','cherry','apple']
if 'banana' in mylist:
    print('Yes')
else:
    print('No')

Yes


In [10]:
mylist = ['banana','cherry','apple']
if 'Orange' in mylist:
    print('Yes')
else:
    print('No')

No


In [11]:
# check list length
print("check list length:")
mylist = ["banana", "cherry", "apple"]
mylist1 = len(mylist)
print(mylist1)

check list length:
3


In [12]:
mylist = ["banana", "cherry", "apple"]
print(len(mylist))

3


In [13]:
# appened function
mylist = ["banana", "cherry", "apple"]
mylist.append('lemon')
print(mylist)

['banana', 'cherry', 'apple', 'lemon']


In [14]:
# insert function
mylist = ["banana", "cherry", "apple"]
mylist.insert(1,'bluebarry')
print(mylist)

['banana', 'bluebarry', 'cherry', 'apple']


In [15]:
# use pop for remove last element
mylist = ["banana", "cherry", "apple"]
mylist.pop()
print(mylist)

['banana', 'cherry']


In [17]:
# remove function
mylist = ["banana", "cherry", "apple"]
mylist.remove('cherry')
print(mylist)

['banana', 'apple']


In [19]:
# reverse function
mylist = ["banana", "cherry", "apple"]
mylist.reverse()
print(mylist)

['apple', 'cherry', 'banana']


In [20]:
# sort function
mylist = ["banana", "cherry", "apple"]
mylist.sort()
print(mylist)

['apple', 'banana', 'cherry']


In [21]:
mylist = [5, 9, 3, 4, -6, -9, -2]
mylist.sort()
print(mylist)

[-9, -6, -2, 3, 4, 5, 9]


In [22]:
mylist = [5, 9, 3, 4, -6, -9, -2]
newlist = sorted(mylist)
print(newlist)

[-9, -6, -2, 3, 4, 5, 9]


In [23]:
# multiple list
mylist = [0] * 5
print(mylist)

[0, 0, 0, 0, 0]


In [24]:
mylist = [0,1] * 5
print(mylist)

[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]


In [28]:
mylist = [[0,1]] * 5
print(mylist)

[[0, 1], [0, 1], [0, 1], [0, 1], [0, 1]]


In [29]:
# adding list
mylist1 = [1,2,3,4,5]
mylist2 = [6,7,8,9,10]
mylist = mylist1 + mylist2
print(mylist)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [30]:
# slicing index
mylist = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a = mylist[1:5]
print(a)

[2, 3, 4, 5]


In [32]:
mylist = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a = mylist[:5]
print(a)

[1, 2, 3, 4, 5]


In [33]:
mylist = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a = mylist[1:]
print(a)

[2, 3, 4, 5, 6, 7, 8, 9, 10]


In [34]:
mylist = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a = mylist[::1]
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [35]:
# jumping one list
mylist = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a = mylist[::2]
print(a)

[1, 3, 5, 7, 9]


In [36]:
mylist = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a = mylist[::-1]
print(a)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [38]:
# list copying
list_original = ["banana", "cherry", "apple"]
list_copy = list_original
print(list_copy)

['banana', 'cherry', 'apple']


In [37]:
# list copying
list_original = ["banana", "cherry", "apple"]
list_copy = list_original.copy()
list_copy.append('lemon')
print(list_copy)
print(list_original)

['banana', 'cherry', 'apple', 'lemon']
['banana', 'cherry', 'apple']


In [39]:
list_original = ["banana", "cherry", "apple"]
list_copy = list_original[:]
list_copy.append('lemon')
print(list_copy)
print(list_original)

['banana', 'cherry', 'apple', 'lemon']
['banana', 'cherry', 'apple']


In [40]:
mylist = [1,2,3,4,5,6]
b = [i*i for i in mylist]
print(mylist)
print(b)

[1, 2, 3, 4, 5, 6]
[1, 4, 9, 16, 25, 36]


# Tuples: Ordered, immuatable, allows duplicate element

In [41]:
mytuple = ('max',28,'Boston')
print(mytuple)

('max', 28, 'Boston')


In [42]:
mytuple = ('max')
print(type(mytuple))

<class 'str'>


In [43]:
mytuple = tuple(['max',28,'Boston'])
print(mytuple)

('max', 28, 'Boston')


In [44]:
# print with index value
mytuple = tuple(['max',28,'Boston'])
item = mytuple[2]
print(item)

Boston


In [45]:
mytuple = tuple(['max',28,'Boston'])
for i in mytuple:
    print(i)

max
28
Boston


In [46]:
mytuple = tuple(['max',28,'Boston'])
if 'max' in mytuple:
    print('Yes')
else:
    print('No')

Yes


In [47]:
mytuple = ("max", 28, "Boston")
if "hello" in mytuple:
    print("Yes")
else:
    print("No")

No


In [48]:
# length count
mytuple = ('a','p','p','l','e')
mytuple = len(mytuple)
print(mytuple)

5


In [50]:
mytuple = ('a', 'p', 'p', 'l', 'e')
print(mytuple.count('p'))
print(mytuple.count('l'))
print(mytuple.count('o'))
print(mytuple.count('e'))

2
1
0
1


In [51]:
# find index value
mytuple = ('a', 'p', 'p', 'l', 'e')
print(mytuple.index('e'))

4


In [54]:
# print with specific value
print("print with specific value:")
mytuple = (1, 2, 3, 4, 5, 6, 7, 8, 9)
b = mytuple[2:5]
print(b)

print with specific value:
(3, 4, 5)


In [55]:
mytuple = (1, 2, 3, 4, 5, 6, 7, 8, 9)
b = mytuple[:1]
print(b)

(1,)


In [56]:
mytuple = (1, 2, 3, 4, 5, 6, 7, 8, 9)
b = mytuple[::1]
print(b)

(1, 2, 3, 4, 5, 6, 7, 8, 9)


In [57]:
mytuple = (1, 2, 3, 4, 5, 6, 7, 8, 9)
b = mytuple[1:]
print(b)

(2, 3, 4, 5, 6, 7, 8, 9)


In [58]:
mytuple = (1, 2, 3, 4, 5, 6, 7, 8, 9)
b = mytuple[::-1]
print(b)

(9, 8, 7, 6, 5, 4, 3, 2, 1)


In [59]:
mytuple = "Max", 28, "Boston"
name, age,city = mytuple
print(name)
print(age)
print(city)

Max
28
Boston


In [60]:
mytuple = (1, 2, 3, 4, 5, 6)
i1,*i2,i3 = mytuple
print(i1)
print(i3)
print(i2)
print(*i2)

1
6
[2, 3, 4, 5]
2 3 4 5


In [61]:
# showing file size
import sys
mylist = [0,1,2,'hello',True]
mytuple = (0,1,2,'hello',True)
print(sys.getsizeof(mytuple),'bytes')
print(sys.getsizeof(mytuple),'bytes')

80 bytes
80 bytes


In [64]:
# showing execute time
import timeit
print(timeit.timeit(stmt="[0, 1, 2, 3, 4, 5]", number=100000)) 
print(timeit.timeit(stmt="(0, 1, 2, 3, 4, 5)", number=100000))

0.009282200000598095
0.003891500000463566


# Dictionaries: key-Value paris, Unordered, Mutable

In [65]:
# creating ditionaries
mydict = {'name':'max','age':28,'city':'new york'}
print(mydict)

{'name': 'max', 'age': 28, 'city': 'new york'}


In [66]:
mydict1 = dict(name='Mary',age=27,city='Boston')
print(mydict1)

{'name': 'Mary', 'age': 27, 'city': 'Boston'}


In [67]:
mydict1 = dict(name = "Mary", age = 27, city = "Boston")
value = mydict1['age']
print(value)

27


In [68]:
mydict1 = dict(name = "Mary", age = 27, city = "Boston")
value = mydict['city']
print(value)

new york


In [70]:
mydict = dict(name = "Mary", age = 27, city = "Boston")
print(mydict)

mydict["email"] = "coolmax@xyz.com"
print(mydict)

{'name': 'Mary', 'age': 27, 'city': 'Boston'}
{'name': 'Mary', 'age': 27, 'city': 'Boston', 'email': 'coolmax@xyz.com'}


In [71]:
# for remove value
mydict = {"name":"Max", "age":28, "city":"New York"}
print(mydict)
del mydict['name']
print(mydict)

{'name': 'Max', 'age': 28, 'city': 'New York'}
{'age': 28, 'city': 'New York'}


In [73]:
# for remove value
mydict = {"name":"Max", "age":28, "city":"New York"}
print(mydict)
mydict.pop('age')
print(mydict)

{'name': 'Max', 'age': 28, 'city': 'New York'}
{'name': 'Max', 'city': 'New York'}


In [74]:
# for remove value
mydict = {"name":"Max", "age":28, "city":"New York"}
print(mydict)
mydict.popitem()
print(mydict)

{'name': 'Max', 'age': 28, 'city': 'New York'}
{'name': 'Max', 'age': 28}


In [75]:
# using if statement
mydict = {"name":"Max", "age":28, "city":"New York"}
if 'name' in mydict:
    print(mydict['name'])

Max


In [76]:
# using try catch statement
mydict = {"name":"Max", "age":28, "city":"New York"}
try:
    print(mydict['lastname'])
except:
    print('error')

error


In [77]:
# using for loop
mydict = {"name":"Max", "age":28, "city":"New York"}
for key in mydict:
    print(key)

name
age
city


In [78]:
mydict = {"name":"Max", "age":28, "city":"New York"}
for key in mydict.values():
    print(key)

Max
28
New York


In [79]:
# using copy
mydict = {"name":"Max", "age":28, "city":"New York"}
mydict1 =  mydict
print(mydict1)

{'name': 'Max', 'age': 28, 'city': 'New York'}


In [80]:
mydict = {"name":"Max", "age":28, "city":"New York"}
mydict1 = mydict
mydict1["email"] = "max@xyz.com"
print(mydict1)
print(mydict)

{'name': 'Max', 'age': 28, 'city': 'New York', 'email': 'max@xyz.com'}
{'name': 'Max', 'age': 28, 'city': 'New York', 'email': 'max@xyz.com'}


In [81]:
# actual copy
print("using actual cop function:")
mydict = {"name":"Max", "age":28, "city":"New York"}
mydict1 = mydict.copy()
mydict1["email"] = "max@xyz.com"
print(mydict)
print(mydict1)

using actual cop function:
{'name': 'Max', 'age': 28, 'city': 'New York'}
{'name': 'Max', 'age': 28, 'city': 'New York', 'email': 'max@xyz.com'}


In [82]:
mydict = {"name":"Max", "age":28, "city":"New York"}
mydict1 = dict(mydict)
mydict1["email"] = "max@xyz.com"
print(mydict)
print(mydict1)

{'name': 'Max', 'age': 28, 'city': 'New York'}
{'name': 'Max', 'age': 28, 'city': 'New York', 'email': 'max@xyz.com'}


In [84]:
# update dictionaries
mydict = {"name":"Max", "age":28, "email":"max@xyz.com"}
mydict1 = dict(name = "Marry", age = 27, city = "Boston")
mydict.update(mydict1)
print(mydict)

{'name': 'Marry', 'age': 27, 'email': 'max@xyz.com', 'city': 'Boston'}


In [86]:
# integer data types
mydict = {3:9, 6:36, 9:81}
print(mydict)

{3: 9, 6: 36, 9: 81}


In [88]:
mytuple = (8,7)
mydict = {mytuple: 15}
print(mydict)

{(8, 7): 15}


# Sets: unordered, mutable, no duplicates

In [89]:
myset = {1,2,3,4,5,6}
print(myset)

{1, 2, 3, 4, 5, 6}


In [90]:
myset = {1,2,3,1,2,4}
print(myset)

{1, 2, 3, 4}


In [92]:
myset = {'hello','world','hello'}
print(myset)

{'hello', 'world'}


In [93]:
myset = {}
print(myset)

{}


In [94]:
myset = {}
print(type(myset))

<class 'dict'>


In [95]:
myset = set()
myset.add(1)
myset.add(2)
myset.add(3)
print(myset)

{1, 2, 3}


In [96]:
myset = set()
myset.add(1)
myset.add(2)
myset.add(3)
myset.discard(3)
print(myset)

{1, 2}


In [97]:
# use pop function
myset = set()
myset.add(1)
myset.add(2)
myset.add(3)
myset.pop()
print(myset)

{2, 3}


In [98]:
# using for loop
myset = set()
myset.add(1)
myset.add(2)
myset.add(3)
for x in myset:
    print(x)

1
2
3


In [99]:
# if statement
myset = set()
myset.add(1)
myset.add(2)
myset.add(3)
if 3 in myset:
    print("Yes")

Yes


In [100]:
myset = set()
myset.add(1)
myset.add(2)
myset.add(3)
if 4 in myset:
    print("No")

In [101]:
# uning unions function
odds = {1, 3, 5, 7, 9}
evens = {0, 2, 4, 6, 8}
prims = {2, 3, 5, 7, 11}
unions = odds.union(evens)
print(unions)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}


In [103]:
# using intersection functions
odds = {1, 3, 5, 7, 9}
evens = {0, 2, 4, 6, 8}
prims = {2, 3, 5, 7, 11}
intersections = odds.intersection(evens)
print(intersections)
intersections = odds.intersection(prims)
print(intersections)

set()
{3, 5, 7}


In [104]:
# using differnce function
setA = {1, 2, 3, 4, 5, 6, 7, 8, 9}
setB = {1, 2, 3, 10, 11, 12}
difference = setA.difference(setB)
print(difference)

{4, 5, 6, 7, 8, 9}


In [105]:
setA = {1, 2, 3, 4, 5, 6, 7, 8, 9}
setB = {1, 2, 3, 10, 11, 12}
difference = setB.difference(setA)
print(difference)

{10, 11, 12}


In [106]:
# using symmetric difference function
setA = {1, 2, 3, 4, 5, 6, 7, 8, 9}
setB = {1, 2, 3, 10, 11, 12}
symmetric_difference = setA.symmetric_difference(setB)
print(symmetric_difference)

{4, 5, 6, 7, 8, 9, 10, 11, 12}


In [107]:
# using update function
setA = {1, 2, 3, 4, 5, 6, 7, 8, 9}
setB = {1, 2, 3, 10, 11, 12}
update = setA.update(setB)
print(update)

None


In [108]:
# using intersection update function
setA = {1, 2, 3, 4, 6, 6, 7, 8, 9}
setB = {1, 2, 3, 10, 11, 12}
setA.intersection_update(setB)
print(setA)

{1, 2, 3}


In [109]:
# using difference update function
setA = {1, 2, 3, 4, 5, 6, 7, 8, 9}
setB = {1, 2, 3, 10, 11, 12}
setA.difference_update(setB)
print(setA)

{4, 5, 6, 7, 8, 9}


In [110]:
setA = {1, 2, 3, 4, 5, 6, 7, 8, 9}
setB = {1, 2, 3, 10, 11, 12}
setB.difference_update(setA)
print(setB)

{10, 11, 12}


In [111]:
# using symmetric difference update
setA = {1, 2, 3, 4, 6, 6, 7, 8, 9}
setB = {1, 2, 3, 10, 11, 12}
setA.symmetric_difference_update(setB)
print(setA)

{4, 6, 7, 8, 9, 10, 11, 12}


In [112]:
# using issubset function
setA = {1, 2, 3, 4, 5, 6}
setB = {1, 2, 3}
print(setB.issubset(setA))

True


In [113]:
# using issupperset function
setA = {1, 2, 3, 4, 5, 6, 7, 8}
setB = {1, 2, 3, 4, 5, 6, 7}
print(setB.issuperset(setA))

False


In [114]:
setA = {1, 2, 3, 4, 5, 6, 7, 8}
setB = {1, 2, 3, 4, 5, 6, 7, 8}
print(setB.issuperset(setA))

True


In [115]:
# using isdisjoint section
setA = {1, 2, 3, 4, 5, 6}
setB = {1, 2, 3}
print(setA.isdisjoint(setB))

False


In [116]:
setA = {1, 2, 3, 4, 5, 6}
setC = {7, 8}
print(setA.isdisjoint(setC))

True


In [117]:
# using copy function
setA = {1,2,3,4,5,6}
setB = setA
print(setB)

{1, 2, 3, 4, 5, 6}


In [118]:
setA = {1, 2, 3, 4, 5, 6}
setB = setA
setB.add(7)
print(setB)
print(setA)

{1, 2, 3, 4, 5, 6, 7}
{1, 2, 3, 4, 5, 6, 7}


In [120]:
setA = {1, 2, 3, 4, 5, 6}
setB = setA.copy()
setB.add(7)
print(setB)
print(setA)

{1, 2, 3, 4, 5, 6, 7}
{1, 2, 3, 4, 5, 6}


In [121]:
# using frozen set function
frozen = frozenset([1,2,3,4])
print(frozen)

frozenset({1, 2, 3, 4})


# String: ordered, immatuable, text representation

In [1]:
import string
from time import time
from tracemalloc import start

In [2]:
mystring = 'hello world'
print(mystring)

hello world


In [3]:
# print multiline string
mystring = """hello
world"""
print(mystring)

hello
world


In [4]:
mystring = """hello \
world"""
print(mystring)

hello world


In [6]:
# using index function
mystring = "hello world"

mystring1 = mystring[0]
print(mystring1)

mystring1 = mystring[-2]
print(mystring1)

mystring1 = mystring[-1]
print(mystring1)

h
l
d


In [7]:
# using substring function
mystring = 'hello world'
mystring1 = mystring[1:5]
print(mystring1)
mystring1 = mystring[::2]
print(mystring1)

ello
hlowrd


In [8]:
# concatenate string
mystring1 = "hello"
mystring2 = "world"
mystring3 = mystring1 + " " + mystring2
print(mystring3)

hello world


In [9]:
# using for loop
mystring1 = 'hello'
for i in mystring1:
    print(i)

h
e
l
l
o


In [10]:
# using if statement
print("using if statement:")
mystring1 = "hello"
if 'h' in mystring1:
    print("yes")
else:
    print("no")

using if statement:
yes


In [11]:
# using strip function for remove white space
mystring = '     hello world'
mystring1 = mystring.strip()
print(mystring1)

hello world


In [12]:
# using startswitch function
mystring = 'hello world'
print(mystring.startswith('hello'))
print(mystring.startswith('world'))

True
False


In [13]:
# using endswith function
mystring = 'hello world'
print(mystring.endswith('hello'))
print(mystring.endswith('world'))

False
True


In [15]:
# using find function
mystring = 'hello world'
mystring1 = mystring.find('o')
print(mystring1)
mystring1 = mystring.find('pp')
print(mystring1)

4
-1


In [16]:
# using count function
mystring = 'hello world'
mystring1 = mystring.count('o')
print(mystring1)

2


In [17]:
# using replace function
mystring = 'hello world'
mystring1 = mystring.replace('world','universe')
print(mystring1)

hello universe


In [18]:
# using split function
mystring = 'how are you doing'
mystring1 = ''.join(mystring)
print(mystring1)

how are you doing


In [19]:
# creating multiple list
print("creating multiple list:")
mystring = ["a"] * 6
print(mystring)

creating multiple list:
['a', 'a', 'a', 'a', 'a', 'a']


In [22]:
# using join function
# right method
mystring = ['a'] * 6
print(mystring)
mystring1 = ''.join(mystring)
print(mystring1)

['a', 'a', 'a', 'a', 'a', 'a']
aaaaaa


In [25]:
from timeit import default_timer as timer
mystring = ['a'] * 6
print(mystring)
start = time()
mystring1 = ''.join(mystring)
stop = timer()
print(mystring1)
print(stop - start)

['a', 'a', 'a', 'a', 'a', 'a']
aaaaaa
-1696257690.1884573


In [26]:
# use % function
var = 'Tom'
mystring = 'the variable is %s' % var
print(mystring)

the variable is Tom


In [27]:
var = 3
mystring = 'the variable is %d' % var
print(mystring)

the variable is 3


In [28]:
var = 3.1416
mystring = "the variable is %.2f" % var
print(mystring)

the variable is 3.14


In [29]:
# use format method
var = 3.1416
mystring = 'the variable is {}'.format(var)
print(mystring)

the variable is 3.1416


In [30]:
var = 3.1416
var1 = 'circle'
mystring = 'the variable is {} and {} '.format(var,var1)
print(mystring)

the variable is 3.1416 and circle 


In [31]:
# use f-string method
var = 3.1416
var1 = 'circle'
mystring = f'the variable is {var} and {var1}'
print(mystring)

the variable is 3.1416 and circle


In [32]:
var = 3.1416
var1 = 'circle'
mystring = f'the variable is {var * 2} and {var1}'
print(mystring)

the variable is 6.2832 and circle


# Collection: Counter, namedtuple, OrderedDict, deque

In [1]:
from collections import Counter
from collections import defaultdict
from collections import namedtuple

In [3]:
a = 'aaaaabbbbccc'
mycounter = Counter(a)
print(mycounter)

Counter({'a': 5, 'b': 4, 'c': 3})


In [5]:
print(mycounter.items())

dict_items([('a', 5), ('b', 4), ('c', 3)])


In [4]:
print(mycounter.keys())

dict_keys(['a', 'b', 'c'])


In [6]:
print(mycounter.values())

dict_values([5, 4, 3])


In [7]:
print(mycounter.most_common(2))

[('a', 5), ('b', 4)]


In [8]:
print(mycounter.most_common(1)[0][0])

a


In [9]:
print(list(mycounter.elements()))

['a', 'a', 'a', 'a', 'a', 'b', 'b', 'b', 'b', 'c', 'c', 'c']


In [12]:
# using multiple variable values
Point = namedtuple('Point','x,y')
pt = Point(1, -4)
print(pt)

Point(x=1, y=-4)


In [13]:
point = ('x,y')
pt = Point(1, -4)
print(pt)

Point(x=1, y=-4)


In [14]:
from collections import OrderedDict
# order dectionaries
orderdict = OrderedDict()
orderdict['a'] = 1
orderdict['b'] = 2
orderdict['c'] = 3
orderdict['d'] = 4
orderdict['e'] = 5
print(orderdict)

OrderedDict([('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5)])


In [15]:
# default directories
d = defaultdict(int)
d['a'] = 1
d['b'] = 2
print(d['a'])
print(d['c'])

1
0


In [16]:
d = defaultdict(float)
d['a'] = 1
d['b'] = 2
print(d['a'])
print(d['c'])

1
0.0


In [17]:
from collections import deque
# using deque function
d = deque()
d.append(1)
d.append(2)
print(d)

deque([1, 2])


In [18]:
d = deque()
d.append(1)
d.append(2)
d.appendleft(3)
print(d)

deque([3, 1, 2])


In [19]:
# using deque with pop function
d = deque()
d.append(1)
d.append(2)
d.append(3)
d.pop()
print(d)

deque([1, 2])


In [20]:
d = deque()
d.append(1)
d.append(2)
d.append(3)
d.popleft()
print(d)

deque([2, 3])


In [21]:
# using extend function
d = deque()
d.append(1)
d.append(2)
d.append(3)
d.extend([4,5,6])
print(d)

deque([1, 2, 3, 4, 5, 6])


In [22]:
d = deque()
d.append(1)
d.append(2)
d.append(3)
d.extendleft([4,5,6])
print(d)

deque([6, 5, 4, 1, 2, 3])


In [24]:
# rotate function
d = deque()
d.append(1)
d.append(2)
d.append(3)
d.extend([4,5,6])
d.rotate(1)
print(d)

deque([6, 1, 2, 3, 4, 5])


In [25]:
d = deque()
d.append(1)
d.append(2)
d.append(3)
d.extend([4,5,6])
d.rotate(2)
print(d)

deque([5, 6, 1, 2, 3, 4])


In [26]:
d = deque()
d.append(1)
d.append(2)
d.append(3)
d.extend([4,5,6])
d.rotate(-1)
print(d)

deque([2, 3, 4, 5, 6, 1])


# Itertools: product, permutations, combinations, accumulate, groupby, and infinite itertors

In [27]:
from audioop import mul
from itertools import product

In [28]:
# product tools
a = [1,2]
b = [3,4]
prod = product(a,b)
print(list(prod))

[(1, 3), (1, 4), (2, 3), (2, 4)]


In [29]:
a = [1,2]
b = [3,4]
prod = product(a,b, repeat=2)
print(list(prod))

[(1, 3, 1, 3), (1, 3, 1, 4), (1, 3, 2, 3), (1, 3, 2, 4), (1, 4, 1, 3), (1, 4, 1, 4), (1, 4, 2, 3), (1, 4, 2, 4), (2, 3, 1, 3), (2, 3, 1, 4), (2, 3, 2, 3), (2, 3, 2, 4), (2, 4, 1, 3), (2, 4, 1, 4), (2, 4, 2, 3), (2, 4, 2, 4)]


In [32]:
from itertools import permutations
# using permutations
a = [1,2,3]
perm = permutations(a)
print(list(perm))

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


In [33]:
# with different ordering
a = [1,2,3]
perm = permutations(a,2)
print(list(perm))

[(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]


In [34]:
from itertools import combinations
# using combinations
a = [1,2,3,4]
comb = combinations(a,2)
print(list(comb))

[(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]


In [35]:
from itertools import combinations
from itertools import combinations_with_replacement
# using combination with replacement
a = [1,2,3,4]
comb = combinations_with_replacement(a,2)
print(list(comb))

[(1, 1), (1, 2), (1, 3), (1, 4), (2, 2), (2, 3), (2, 4), (3, 3), (3, 4), (4, 4)]


In [39]:
from itertools import accumulate
# using accumulate function
a = [1, 2, 3, 4,5]
acc = accumulate(a)
print(a)
print(list(acc))

[1, 2, 3, 4, 5]
[1, 3, 6, 10, 15]


In [40]:
from itertools import accumulate
import operator
# using accumulate with operator function
print("using accumulate with operator function:")
a = [1, 2, 3, 4]
acc = accumulate(a, func=operator.mul)
print(a)
print(list(acc))

using accumulate with operator function:
[1, 2, 3, 4]
[1, 2, 6, 24]


In [41]:
a = [1, 2, 3, 4]
acc = accumulate(a, func=operator.add)
print(a)
print(list(acc))

[1, 2, 3, 4]
[1, 3, 6, 10]


In [42]:
a = [1, 2, 3, 4]
acc = accumulate(a, func=operator.sub)
print(a)
print(list(acc))

[1, 2, 3, 4]
[1, -1, -4, -8]


In [43]:
a = [1, 2, 5, 3, 4]
acc = accumulate(a, func=max)
print(a)
print(list(acc))

[1, 2, 5, 3, 4]
[1, 2, 5, 5, 5]


In [45]:
from itertools import groupby
# using groupby function
def smallerThen3(x):
    return x < 3
a = [1, 2, 3, 4]
group_obj = groupby(a, key=smallerThen3)
for key, value in group_obj:
    print(key, list(value))

True [1, 2]
False [3, 4]


In [46]:
def smallerThen3(x):
    return x < 3
a = [1, 2, 3, 4]
group_obj = groupby(a, key=lambda x: x < 3)
for key, value in group_obj:
    print(key, list(value))

True [1, 2]
False [3, 4]


In [47]:
persons = [{'name': 'Tim', 'age': 25}, {'name': 'Dan', 'age': 25}, {'name': 'Lisa', 'age': 27}, {'name': 'claire', 'age': 28}]
group_obj = groupby(persons, key=lambda x: x['age'])
for key, value in group_obj:
    print(key, list(value))

25 [{'name': 'Tim', 'age': 25}, {'name': 'Dan', 'age': 25}]
27 [{'name': 'Lisa', 'age': 27}]
28 [{'name': 'claire', 'age': 28}]


# lambda arguments: expression

In [3]:
from itertools import product

add10 = lambda x:x + 10
print(add10(5))

15


In [4]:
mul = lambda x,y : x+y
print(mul(2,3))

5


In [5]:
mul = lambda x,y:x*y
print(mul(5,7))

35


In [6]:
# using sorted list
point2D = [(1, 2), (15, 1), (5, -1), (10, 4)]
point2D_shorted = sorted(point2D)
print(point2D)
print(point2D_shorted)

[(1, 2), (15, 1), (5, -1), (10, 4)]
[(1, 2), (5, -1), (10, 4), (15, 1)]


In [7]:
# shorted with y index
point2D = [(1, 2), (15, 1), (5, -1), (10, 4)]
point2D_shorted = sorted(point2D, key=lambda x: x[1])
print(point2D)
print(point2D_shorted)

[(1, 2), (15, 1), (5, -1), (10, 4)]
[(5, -1), (15, 1), (1, 2), (10, 4)]


In [8]:
# shorted with y index
point2D = [(1, 2), (15, 1), (5, -1), (10, 4)]
point2D_shorted = sorted(point2D, key=lambda x: x[1])
print(point2D)
print(point2D_shorted)

[(1, 2), (15, 1), (5, -1), (10, 4)]
[(5, -1), (15, 1), (1, 2), (10, 4)]


In [9]:
point2D = [(1, 2), (15, 1), (5, -1), (10, 4)]
point2D_shorted = sorted(point2D, key=lambda x: x[0] + x[1])
print(point2D)
print(point2D_shorted)

[(1, 2), (15, 1), (5, -1), (10, 4)]
[(1, 2), (5, -1), (10, 4), (15, 1)]


In [10]:
# using map(func,seq) function
a = [1,2,3,4]
b = map(lambda x:x * 2,a)
print(list(a))
print(list(b))

[1, 2, 3, 4]
[2, 4, 6, 8]


In [11]:
# second method
a = [1,2,3,4]
c = [x * 2 for x in a]
print(a)
print(list(c))

[1, 2, 3, 4]
[2, 4, 6, 8]


In [12]:
# using filter(func,seq) function
a = [1,2,3,4]
b = map(lambda x:x % 2 == 0,a)
print(list(b))

[False, True, False, True]


In [14]:
# using filter(func, seq) function
a = [1,2,3,4]
b = filter(lambda x:x % 2 == 0,a)
print(list(b))

[2, 4]


In [16]:
# second method
a = [1, 2, 3, 4]
c = [x for x in a if x % 2 == 0]
print(list(c))

[2, 4]


In [17]:
from functools import reduce
# using reduce(func,seq) function
a = [1,2,3,4]
b = reduce(lambda x,y:x*y,a)
print(b)

24


In [18]:
a = [1,2,3,4]
b = reduce(lambda x,y: x+y,a)
print(b)

10


# Error & Exceptions

In [1]:
x = -5
if x < 0:
    raise Exception('x should be posetive')

Exception: x should be posetive

In [2]:
x = 5
if x < 5:
    raise Exception('x should be posetive')

In [3]:
# using assertion error
x = -5
assert (x >= 0), 'x is not posetive'

AssertionError: x is not posetive

In [4]:
# zero divison error
a = 5/0

ZeroDivisionError: division by zero

In [5]:
# using try and except
try:
    a = 5 / 0
except:
    print('an error detected')

an error detected


In [6]:
# using try except error with massage
try:
    a = 5/0
except Exception as e:
    print(e)

division by zero


In [7]:
# using multiple exception
try:
    a = 5 / 1
    b = a + '10'
except ZeroDivisionError as e:
    print(e)
except TypeError as e:
    print(e)

unsupported operand type(s) for +: 'float' and 'str'


In [8]:
# using try except with else
try:
    a = 5 / 1
    b = a + 10
except ZeroDivisionError as e:
    print(e)
except TypeError as e:
    print(e)
else:
    print("everything is fine")

everything is fine


In [9]:
# using try except else and finally
try:
    a = 5/0
    b = a+10
except TypeError as e:
    print(e)
except ZeroDivisionError as e:
    print(e)
else:
    print('everything is fine')
finally:
    print('cleaning up....')

division by zero
cleaning up....


In [10]:
try:
    a = 5/1
    b = a+10
except TypeError as e:
    print(e)
except ZeroDivisionError as e:
    print(e)
else:
    print('everything is fine')
finally:
    print('cleaning up...')

everything is fine
cleaning up...


In [11]:
# value check  
class ValueTooHighError(Exception):
    pass
def test_value(x):
    if x > 100:
        raise ValueTooHighError("value is too high")
test_value(101)

ValueTooHighError: value is too high

In [12]:
class ValueTooHighError(Exception):
    pass
def test_value(x):
    if x > 100:
        raise ValueTooHighError("value is too high")
try:
    test_value(200)
except ValueTooHighError as e:
    print(e)

value is too high


In [13]:
class ValueTooHighError(Exception):
    pass
class ValueTooSmallError(Exception):
    def __init__(self, message, value):
        self.message = message
        self.value = value
def test_value(x):
    if x > 100:
        raise ValueTooHighError("value is too high")
    if x < 100:
        raise ValueTooSmallError("value is too small", x)
try:
    test_value(20)
except ValueTooHighError as e:
    print(e)
except ValueTooSmallError as e:
    print(e.message, e.value)

value is too small 20


# Random Numbers

In [15]:
import random
a = random.random()
print(a)

0.20348023589779474


In [16]:
# random number with range
a = random.uniform(1,10)
print(a)

8.991672278895617


In [17]:
a = random.uniform(9,10)
print(a)

9.639756508851715


In [18]:
# random number with randint
a = random.randint(1,10)
print(a)

a = random.randint(7,10)
print(a)

4
7


In [20]:
# random number with randrange
a = random.randrange(1,10)
print(a)

a = random.randrange(7,10)
print(a)

6
8


In [21]:
# random number with normalvarite
a = random.normalvariate(0,1)
print(a)

-1.712477304704416


In [22]:
# random choice
mylist = list('ABCDEF')
a = random.choice(mylist)
print(mylist)
print(a)

['A', 'B', 'C', 'D', 'E', 'F']
D


In [24]:
# random sample wiht element
mylist = list('ABCDE')
a = random.sample(mylist,3)
print(mylist)
print(a)

['A', 'B', 'C', 'D', 'E']
['B', 'A', 'C']


In [25]:
# random sample with multiple element
mylist = list('ABCDEF')
a = random.sample(mylist,k=3)
print(mylist)
print(a)

['A', 'B', 'C', 'D', 'E', 'F']
['F', 'D', 'B']


In [27]:
# random sample with shuffle element
mylist = list("ABCDEF")
a = random.shuffle(mylist)
print(mylist)

['F', 'C', 'E', 'B', 'D', 'A']
None


In [28]:
# using ranodm seed
random.seed(1)
print(random.random())
print(random.randint(1,10))

0.13436424411240122
2


In [29]:
random.seed(1)
print(random.random())
print(random.randint(1,10))

0.13436424411240122
2


In [30]:
# using random seed
random.seed(1)
print(random.random())
print(random.randint(1, 10))

0.13436424411240122
2


In [31]:
random.seed(2)
print(random.random())
print(random.randint(1,10))

0.9560342718892494
1


In [32]:
random.seed(1)
print(random.random())
print(random.randint(1, 10))

0.13436424411240122
2


In [33]:
random.seed(2)
print(random.random())
print(random.randint(1, 10))

0.9560342718892494
1


In [34]:
# secrets number
import secrets
a = secrets.randbelow(10)
print(a)

8


In [35]:
# using randbits function
a = secrets.randbits(4)
print(a)

8


In [36]:
mylist = list('ABCDEFGH')
a = secrets.choice(mylist)
print(a)

B


In [37]:
# using number library rand function
import numpy as np
a = np.random.rand(3)
print(a)

[0.26100775 0.37871653 0.38274606]


In [38]:
# using numpy library with randint function
a = np.random.randint(0,10,3)
print(a)

[9 6 6]


In [39]:
# using numby library with multi diemention array
a = np.random.randint(0,10,(3,4))
print(a)

[[3 2 6 9]
 [2 9 5 4]
 [8 0 4 2]]


In [41]:
# using numpy library wiht shuffle function
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
np.random.shuffle(a)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [42]:
# using numby library with seed function
np.random.seed(1)
print(np.random.rand(3,3))

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]


In [43]:
np.random.seed(1)
print(np.random.rand(3,3))

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]


# Decorator

In [44]:
def start_and_decorator(func):
    def wrapper():
        print("start")
        func()
        print("end")
    return wrapper
def print_name():
    print("alex")
print_name = start_and_decorator(print_name)
print_name()

start
alex
end


In [45]:
# with @ method
print("with @ method:")
def start_end_decorator(func):
    def wrapper():
        print("start")
        func()
        print("end")
    return wrapper
@start_end_decorator
def print_name():
    print("alex")

with @ method:


In [46]:
# with value add function
print("with value add function")
def start_and_decorator(func):
    def wrapper(*args, **kwargs):
        print("start")
        result = func(*args, **kwargs)
        print("end")
        return result
    return wrapper
@start_and_decorator
def add5(x):
    return x + 5
result = add5(10)
print(result)

with value add function
start
end
15


In [47]:
# with identify function
def start_and_decorator(func):
    def wrapper(*args, **kwargs):
        print("start")
        result = func(*args, **kwargs)
        print("end")
        return result
    return wrapper
@start_and_decorator
def add5(x):
    return x + 5
print(help(result))
print(add5.__name__)

Help on int object:

class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
 |  
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |  
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |  
 |  Built-in subclasses:
 |      bool
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      True if self else False
 |

In [48]:
# with identify function
import functools
def try_decorator(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        # Do...
        result = func(*args, **kwargs)
        # Do...
        return result
    return wrapper
@start_and_decorator
def add5(x):
    return x + 5
print(help(result))

Help on int object:

class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
 |  
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |  
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |  
 |  Built-in subclasses:
 |      bool
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      True if self else False
 |

In [49]:
# simple decorators
print("simple decorators:")
import functools
def repeat(num_times):
    def decorator_repeat(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            for _ in range(num_times):
                result = func(*args, **kwargs)
            return result
        return wrapper
    return decorator_repeat
@repeat(num_times = 3)
def greet(name):
    print(f'Hello {name}')
greet("Alex")

simple decorators:
Hello Alex
Hello Alex
Hello Alex


In [50]:
# nested decorators
print("nested decorators:")
import functools
def start_end_decorator(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        print("Start")
        result = func(*args, **kwargs)
        print("End")
        return result
    return wrapper
def debug(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        args_repr = [repr(a) for a in args]
        kwargs_repr = [f"{k}={v!r}" for k, v in kwargs.items()]
        signature = ", ".join(args_repr + kwargs_repr)
        print(f"Calling {func.__name__}({signature})")
        result = func(*args, **kwargs)
        print(f"{func.__name__!r}returned {result!r}")
        return result
    return wrapper
@debug
@start_end_decorator
def say_hello(name):
    greeting = f'Hello{name}'
    print(greeting)
    return greeting
say_hello("alex")

nested decorators:
Calling say_hello('alex')
Start
Helloalex
End
'say_hello'returned 'Helloalex'


'Helloalex'

In [51]:
# function decorator
print("function decorator:")
class CountCalls:
    def __init__(self, func):
        self.func = func
        self.num_calls = 0
    def __call__(self, *args, **kwargs):
        print("Hi there")
cc = CountCalls(None)
cc()
@CountCalls
def say_hello():
    print("hello")

function decorator:
Hi there


In [52]:
# function decorator
print("function decorator:")
class CountCalls:
    def __init__(self, func):
        self.func = func
        self.num_calls = 0
    def __call__(self, *args, **kwargs):
        self.num_calls += 1
        print(f"Hi there{self.num_calls} times")
        return self.func(*args, **kwargs)
@CountCalls
def say_hello():
    print("hello")
say_hello()

function decorator:
Hi there1 times
hello


In [53]:
# function decorator
print("function decorator:")
class CountCalls:
    def __init__(self, func):
        self.func = func
        self.num_calls = 0
    def __call__(self, *args, **kwargs):
        self.num_calls += 1
        print(f"Hi there{self.num_calls} times")
        return self.func(*args, **kwargs)
@CountCalls
def say_hello():
    print("hello")
say_hello()
say_hello()

function decorator:
Hi there1 times
hello
Hi there2 times
hello


# Generators

In [54]:
def mygenarator():
    yield 1
    yield 2
    yield 3
g = mygenarator()
print(g)

<generator object mygenarator at 0x00000180C3A9E090>


In [55]:
def mygenarator():
    yield 1
    yield 2
    yield 3
g = mygenarator()
for i in g:
    print(i)

1
2
3


In [65]:
# generators
def mygenarator():
    yield 1
    yield 2
    yield 3
g = mygenarator()
value = next(g)
print(value)
value = next(g)
print(value)
value = next(g)
print(value)

1
2
3


In [66]:
# generators
def mygenarator():
    yield 1
    yield 2
    yield 3
g = mygenarator()
print(sorted(g))

[1, 2, 3]


In [67]:
# generators
def countdown(num):
    print("Starting")
    while num > 0:
        yield num
        num -= 1
cd = countdown(4)
value = next(cd)
print(value)
print(next(cd))

Starting
4
3


In [68]:
# generators
def first(n):
    nums = []
    num = 0
    while num < n:
        nums.append(num)
        num += 1
    return nums
print(first(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [69]:
# genarators
def firstn(n):
    nums = []
    num = 0
    while num < n:
        nums.append(num)
        num += 1
    return nums
def first_genarator(n):
    num = 0
    while num < n:
        yield num
        num += 1
print(sum(firstn(10)))
print(sum(first_genarator(10)))

45
45


In [70]:
# generartor with memory value
import sys
def firstn(n):
    nums = []
    num = 0
    while num < n:
        nums.append(num)
        num += 1
    return nums
def first_generator(n):
    num = 0
    while num < n:
        yield num
        num += 1
print(sys.getsizeof(firstn(10000000)))
print(sys.getsizeof(first_generator(10000000)))

89095160
200


In [71]:
# generator with fibonacci
def fibonacci(limit):
    a, b = 0, 1
    while a < limit:
        yield a
        a, b = b, a + b
fib = fibonacci(30)
for i in fib:
    print(i)

0
1
1
2
3
5
8
13
21


In [72]:
# generator
mygenarator = (i for i in range(10) if i % 2 == 0)
for i in mygenarator:
    print(i)

0
2
4
6
8


In [73]:
# create generator with size
import sys
mygenarator = (i for i in range(100000) if i % 2 == 0)
print(sys.getsizeof(mygenarator))
mylist = [i for i in range(100000) if i % 2 == 0]
print(sys.getsizeof(mylist))

208
444376


# Multithreading vs Multiprocessing

In [75]:
# multiprocessing
print("Start:")
from multiprocessing import Process
import os
import time
def square_numbers():
    for i in range(100):
        i * i
        time.sleep(0.1)
processes = []
num_processes = os.cpu_count()
'''create processes'''
for i in range(num_processes):
    p = Process(target=square_numbers)
    processes.append(p)
'''start'''
for p in processes:
    p.start()
'''join'''
for p in processes:
    p.join()
print("end main")

Start:
end main


In [76]:
# multithreading
print("Start:")
from threading import Thread
import os
import time
def square_numbers():
    for i in range(100):
        i * i
        time.sleep(0.1)
threads = []
num_threads = 10
'''create processes'''
for i in range(num_threads):
    t = Thread(target=square_numbers)
    threads.append(t)
'''start'''
for t in threads:
    t.start()
'''join'''
for t in threads:
    t.join()
print("end main")

Start:
end main


# Threading

In [78]:
# multithreading
import time
from threading import Thread

database_value = 0
def increase():
    global database_value
    local_copy = database_value
    local_copy += 1
    time.sleep(0.1)
    database_value = local_copy
if __name__ == "__main__":
    print("start value", database_value)
    thread1 = Thread(target=increase)
    thread2 = Thread(target=increase)
    thread1.start()
    thread2.start()
    thread1.join()
    thread2.join()
    print("end value"+ database_value) 

start value 0


TypeError: can only concatenate str (not "int") to str

In [80]:
# multithreading
print("multithreading:")
import time
from threading import Thread, Lock

database_value = 0
def increase(lock):
    global database_value
    lock.acquire()
    local_copy = database_value
    local_copy += 1
    time.sleep(0.1)
    database_value = local_copy
    lock.release()
if __name__ == "__main__":
    lock = Lock()
    print("start value", database_value)
    thread1 = Thread(target=increase, args=(lock,))
    thread2 = Thread(target=increase, args=(lock,))
    thread1.start()
    thread2.start()
    thread1.join()
    thread2.join()
    print("end value"+ database_value)

multithreading:
start value 0


TypeError: can only concatenate str (not "int") to str

In [81]:
# multithreading
print("multithreading:")
import time
from threading import Thread, Lock

database_value = 0
def increase(lock):
    global database_value
    with lock:
        local_copy = database_value
        local_copy += 1
        time.sleep(0.1)
        database_value = local_copy
        lock.release()
if __name__ == "__main__":
    lock = Lock()
    print("start value", database_value)
    thread1 = Thread(target=increase, args=(lock,))
    thread2 = Thread(target=increase, args=(lock,))
    thread1.start()
    thread2.start()
    thread1.join()
    thread2.join()
    print("end main")

Exception in thread Thread-19 (increase):
Traceback (most recent call last):
  File "c:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "c:\Program Files\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\emon1\AppData\Local\Temp\ipykernel_6116\1041620559.py", line 9, in increase
RuntimeError: release unlocked lock


multithreading:
start value 0


Exception in thread Thread-20 (increase):
Traceback (most recent call last):
  File "c:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "c:\Program Files\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\emon1\AppData\Local\Temp\ipykernel_6116\1041620559.py", line 9, in increase
RuntimeError: release unlocked lock


end main


In [82]:
# multithreading with queue
print("multithreading with queue:")
import time
from threading import Thread, Lock
from queue import Queue

if __name__ == "__main__":
    Q = Queue()
    Q.put(1)
    Q.put(2)
    Q.put(3)
    first = Q.get()
    print(first)
    Q.task_done()
    Q.join()
    print("end main")

multithreading with queue:
1


In [1]:
# multithreading with queue
print("multithreading with queue:")
import time
from threading import Thread, Lock, current_thread
from queue import Queue

def worker(q):
    while True:
        value = q.get()
        '''processing'''
        print(f"in {current_thread().name} got {value}")
        q.task_done()
if __name__ == "__main__":
    Q = Queue()
    run_threads = 10
    for i in range(run_threads):
        thread = Thread(target=worker, args=(q,))
        thread.daemon = True
        thread.start()
    for i in range(1, 21):
        Q.put(i)
    Q.join()        
    print("end main")

multithreading with queue:


NameError: name 'q' is not defined

In [ ]:
# multithreading with queue
print("multithreading with queue:")
import time
from threading import Thread, Lock, current_thread
from queue import Queue

def worker(q):
    while True:
        value = q.get()
        '''processing'''
        print(f"in {current_thread().name} got {value}")
        q.task_done()
if __name__ == "__main__":
    Q = Queue()
    run_threads = 10
    for i in range(run_threads):
        thread = Thread(target=worker, args=(q,))
        thread.daemon = True
        thread.start()
    for i in range(1, 21):
        Q.put(i)
    Q.join()        
    print("end main")

In [2]:
# multithreading with queue
print("multithreading with queue:")
import time
from threading import Thread, Lock
from queue import Queue

def worker(q):
    while True:
        value = q.get()
        '''processing'''
        print(f"in {current_thread().name} got {value}")
        q.task_done()
if __name__ == "__main__":
    Q = Queue()
    run_threads = 10
    for i in range(run_threads):
        thread = Thread(target=worker, args=(q,))
        thread.daemon = True
        thread.start()
    for i in range(1, 21):
        q.put(i)
    q.join()        
    print("end main")

multithreading with queue:


NameError: name 'q' is not defined

In [3]:
# multithreading with queue
print("multithreading with queue:")
import time
from threading import Thread, Lock
from queue import Queue

def worker(q):
    while True:
        value = q.get(q, lock)
        '''processing'''
        print(f"in {current_thread().name} got {value}")
        q.task_done()
if __name__ == "__main__":
    Q = Queue()
    lock = Lock()
    run_threads = 10
    for i in range(run_threads):
        thread = Thread(target=worker, args=(q, lock))
        thread.daemon = True
        thread.start()
    for i in range(1, 21):
        q.put(i)
    q.join()        
    print("end main")

multithreading with queue:


NameError: name 'q' is not defined

In [5]:
# multithreading with queue
print("multithreading with queue:")
import time
from threading import Thread, Lock
from queue import Queue

def worker(q):
    while True:
        value = q.get(q, lock)
        '''processing'''
        print(f"in {current_thread().name} got {value}")
        q.task_done()
        if ...:
            break
if __name__ == "__main__":
    Q = Queue()
    lock = Lock()
    run_threads = 10
    for i in range(run_threads):
        thread = Thread(target=worker, args=(q, lock))
        thread.daemon = False
        thread.start()
    for i in range(1, 21):
        Q.put(i)
    Q.join()        
    print("end main")

multithreading with queue:


NameError: name 'q' is not defined

# Multiprocessing

In [6]:
# multiprocessing
from multiprocessing import Process, Value, Array
import time
def add_100(number):
    for i in range(100):
        time.sleep(0.01)
        number.value += 1
if __name__ == "__main__":
    shared_number = Value("i",0)
    print("Number at beginning is", shared_number.value)
    p1 = Process(target=add_100, args=(shared_number,))
    p2 = Process(target=add_100, args=[shared_number,])
    p1.start()
    p2.start()
    p1.join()
    p2.join()
    print("number at end is", shared_number.value)

Number at beginning is 0
number at end is 0


In [7]:
#multiprocessing
from multiprocessing import Process, Value, Array, Lock
import time
def add_100(number):
    for i in range(100):
        time.sleep(0.01)
        lock.acquire()
        number.value += 1
        lock.release()
if __name__ == "__main__":
    lock = Lock
    shared_number = Value("i",0)
    print("Number at beginning is", shared_number.value)
    p1 = Process(target=add_100, args=(shared_number, lock))
    p2 = Process(target=add_100, args=[shared_number, lock])
    p1.start()
    p2.start()
    p1.join()
    p2.join()
    print("number at end is", shared_number.value)

Number at beginning is 0
number at end is 0


In [8]:
# multiprocessing
from multiprocessing import Process, Value, Array, Lock
import time
def add_100(number, lock):
    for i in range(100):
        time.sleep(0.01)
        with lock:
            number.value += 1
if __name__ == "__main__":
    lock = Lock
    shared_number = Value("i",0)
    print("Number at beginning is", shared_number.value)
    p1 = Process(target=add_100, args=(shared_number, lock))
    p2 = Process(target=add_100, args=[shared_number, lock])
    p1.start()
    p2.start()
    p1.join()
    p2.join()
    print("number at end is", shared_number.value)

Number at beginning is 0
number at end is 0


In [9]:
#  multiprocessing
from multiprocessing import Process, Value, Array, Lock
import time
def add_100(numbers, lock):
    for i in range(100):
        time.sleep(0.01)
        for number in numbers:
            number += 1
if __name__ == "__main__":
    lock = Lock
    shared_array = Array("d", [0.0, 100.0, 200.0])
    print("array at beginning is", shared_array.value)
    p1 = Process(target=add_100, args=(shared_array, lock))
    p2 = Process(target=add_100, args=[shared_array, lock])
    p1.start()
    p2.start()
    p1.join()
    p2.join()
    print("array at end is", shared_array.value)

AttributeError: 'SynchronizedArray' object has no attribute 'value'

In [10]:
# multiprocessing
from multiprocessing import Process, Value, Array, Lock
import time
def add_100(numbers, lock):
    for i in range(100):
        time.sleep(0.01)
        for i in range(len(numbers)):
            numbers[i] += 1
if __name__ == "__main__":
    lock = Lock
    shared_array = Array("d", [0.0, 100.0, 200.0])
    print("array at beginning is", shared_array.value)
    p1 = Process(target=add_100, args=(shared_array, lock))
    p2 = Process(target=add_100, args=[shared_array, lock])
    p1.start()
    p2.start()
    p1.join()
    p2.join()
    print("array at end is", shared_array.value)

AttributeError: 'SynchronizedArray' object has no attribute 'value'

In [11]:
# multiprocessing
from multiprocessing import Process, Value, Array, Lock, Queue
from queue import Queue
import time
def square(numbers, queue):
    for i in numbers:
        queue.put(i*i)
def make_negative(numbers, queue):
    for i in numbers:
        queue.put(-1*i)
if __name__ == "__main__":
    numbers = range[1, 6]
    q = Queue()
    p1 = Process(target=square, args=(numbers, q))
    p2 = Process(target=make_negative, args=(numbers, q))
    p1.start()
    p2.start()
    p1.join()
    p2.join()
    while not q.empty():
        print(q.get())

TypeError: type 'range' is not subscriptable

In [13]:
# process tools multiprocessing
# multiprocessing
from multiprocessing import Process, Value, Array, Lock
import time
def square(numbers, queue):
    for i in numbers:
        queue.put(i*i)
def make_negative(numbers, queue):
    for i in numbers:
        queue.put(-1*i)
if __name__ == "__main__":
    numbers = range(1, 6)
    q = Queue()
    p1 = Process(target=square, args=(numbers, q))
    
    p2 = Process(target=make_negative, args=(numbers,q))
    p1.start()
    p2.start()
    p1.join()
    p2.join()
    while not q.empty():
        print(q.get())

TypeError: cannot pickle '_thread.lock' object

In [15]:
# multiprocessing
from multiprocessing import Pool, Value, Array, Lock
def cube(number):
    return number * number * number
if __name__ == "__main__":
    numbers = range(10)
    pool = Pool()
    '''map, appaly, join, close'''
    result.map(cube, numbers)
    print(result)

NameError: name 'result' is not defined

In [16]:
# multiprocessing
from multiprocessing import Pool, Value, Array, Lock
def cube(number):
    return number * number * number
if __name__ == "__main__":
    numbers = range(10)
    pool = Pool()
    '''map, appaly, join, close'''
    result, pool.map(cube, numbers)
    pool.close()
    pool.join()
    print(result)

NameError: name 'result' is not defined

In [18]:
# multiprocessing
from multiprocessing import Pool, Value, Array, Lock
def cube(number):
    return number * number * number
if __name__ == "__main__":
    numbers = range(10)
    pool = Pool()
    '''map, appaly, join, close'''
    result,pool.map(cube, numbers)
    pool.apply(cube, numbers[0])
    pool.close()
    pool.join()
    print(result)

multiprocessing:


NameError: name 'result' is not defined

# Function

In [19]:
def print_name(name):
    print(name)
print_name('alex')

alex


In [20]:
def foo(a,b,c):
    print(a,b,c)
foo(1,2,3)

1 2 3


In [21]:
# function with value
def foo(a, b, c):
    print(a, b, c)
foo(a=1, b=2, c=3)

1 2 3


In [22]:
# function with different value
def foo(a, b, c):
    print(a, b, c)
foo(1, b=2, c=3)

1 2 3


In [23]:
# function with different value
def foo(a, b, c, d = 4):
    print(a, b, c, d)
foo(1, 2, 3)

1 2 3 4


In [24]:
# function with different value
def foo(a, b, c, d = 4):
    print(a, b, c, d)
foo(1, 2, 3, 7)

1 2 3 7


In [28]:
# funciton with different value
def foo(a,b,*args):
    print(a,b)
    for arg in args:
        print(arg)
foo(1,2,3,4,5,6)

1 2
3
4
5
6


In [29]:
# function with different value
def foo(a,b,*args,**kwargs):
    print(a,b)
    for arg in args:
        print(arg)
        pass
    for key in kwargs:
        print(key,kwargs[key])
foo(1,2,3,4,5,six=6,seven=7)

1 2
3
4
5
six 6
seven 7


In [30]:
# function with different value
print("function with different value:")
def foo(a, b, *args, **kwargs):
    print(a, b)
    for arg in args:
        print(arg)
    for key in kwargs:
        print(key, kwargs[key])
foo(1, 2, 3, 4, 5)

function with different value:
1 2
3
4
5


In [31]:
def foo(a,b,*,c,d):
    print(a,b,c,d)
foo(1,2,c=3,d=4)

1 2 3 4


In [32]:
# function with perameter
print("function with perameter:")
def foo(*args, last):
    for arg in args:
        print(arg)
    print(last)
foo(1, 2, 3, last = 300)

function with perameter:
1
2
3
300


In [33]:
# function
def foo(a,b,c):
    print(a,b,c)
mylist = (0,1,2)
foo(*mylist)

0 1 2


In [35]:
# function with dictionary
def foo(a, b, c):
    print(a, b, c)
my_dict = {"a":1, "b":2, "c":3}
foo(**my_dict)

1 2 3


In [37]:
# function with global variable
def foo():
    global number
    x = number
    number = 3
    print("number inside function",x)
number = 0
foo()
print(number)

number inside function 0
3


In [2]:
# function with mutable object
def foo(a_list):
    a_list.append(4)
my_list = [1, 2, 3]
foo(my_list)
print(my_list)

[1, 2, 3, 4]


In [3]:
def foo(a_list):
    a_list.append(4)
    a_list[0] = -100
my_list = [1, 2, 3]
foo(my_list)
print(my_list)

[-100, 2, 3, 4]


In [4]:
def foo(a_list):
    a_list += [200, 300, 400]
my_list = [1, 2, 3]
foo(my_list)
print(my_list)

[1, 2, 3, 200, 300, 400]


In [5]:
def foo(a_list):
    a_list = a_list + [200, 300, 400]
my_list = [1, 2, 3]
foo(my_list)
print(my_list)

[1, 2, 3]


# Asterisk Operation

In [6]:
# multipication
result = 5 * 7
print(result)

35


In [7]:
# square
result = 2 ** 4
print(result)

16


In [8]:
# create multiple list
zeros = [0] * 10
print(zeros)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [9]:
zeros = [0, 1] * 10
print(zeros)

[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]


In [10]:
# create multiple tuples
zeros = (0, 1) * 10
print(zeros)

(0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1)


In [11]:
# create multiple string
zeros = "ABC" * 10
print(zeros)

ABCABCABCABCABCABCABCABCABCABC


In [12]:
# function with args and kwargs
def foo(a, b, *args, **kwargs):
    print(a, b)
    for arg in args:
        print(arg)
    for key in kwargs:
        print(key, kwargs[key])
foo(1, 2, 3, 4, 5, six = 6, seven = 7)

1 2
3
4
5
six 6
seven 7


In [13]:
# function with asterlick value
def foo(a, b, *, c):
    print(a, b, c)
foo(1, 2, c=3)

1 2 3


In [14]:
# function with list
def foo(a, b, c):
    print(a, b, c)
my_list = [0, 1, 2]
foo(*my_list)

0 1 2


In [15]:
# function with tuple
def foo(a, b, c):
    print(a, b, c)
my_list = [0, 1, 2]
foo(*my_list)

0 1 2


In [16]:
# function with my dict
def foo (a, b, c):
    print(a, b, c)
my_dict = {"a":1, "b":2, "c":3}
foo(**my_dict)

function with my dict:
1 2 3


In [18]:
# its show the last number
numbers = [1, 2, 3, 4, 5, 6]
*beginning,last = numbers
print(beginning)
print(last)

[1, 2, 3, 4, 5]
6


In [19]:
numbers = (1, 2, 3, 4, 5, 6)
*beginning, last = numbers
print(beginning)
print(last)

[1, 2, 3, 4, 5]
6


In [20]:
# its show the middle and last element
numbers = (1, 2, 3, 4, 5, 6)
beginning, *middle, last = numbers
print(beginning)
print(middle)
print(last)

1
[2, 3, 4, 5]
6


In [21]:
# its show the middle, secondlast and last element
numbers = (1, 2, 3, 4, 5, 6)
beginning, *middle, secondlast, last = numbers
print(beginning)
print(middle)
print(secondlast)
print(last)

1
[2, 3, 4]
5
6


In [23]:
# touple and list addition
my_tuple = (1, 2, 3)
my_list = [4, 5, 6]
new_list = [*my_tuple, *my_list]
print(new_list)

[1, 2, 3, 4, 5, 6]


In [24]:
# touple and other addition
my_tuple = (1, 2, 3)
my_set = {4, 5, 6}
new_list = [*my_tuple, *my_set]
print(new_list)

[1, 2, 3, 4, 5, 6]


In [25]:
dict_a = {"a":1, "b":2}
dict_b = {"c":3, "d":4}
my_dict = {**dict_a, **dict_b}
print(my_dict)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}


# Shallow vs Deep Copy

In [26]:
org = 5
cpy = org
cpy = 6
print(cpy)
print(org)

6
5


In [27]:
# default copy
org = [0,1,2,3,4]
cpy = org
cpy[0] = -10
print(cpy)
print(org)

[-10, 1, 2, 3, 4]
[-10, 1, 2, 3, 4]


In [28]:
# shallow copy
import copy
org = [0,1,2,3,4]
cpy = copy.copy(org)
cpy[0] = -10
print(cpy)
print(org)

[-10, 1, 2, 3, 4]
[0, 1, 2, 3, 4]


In [29]:
# shallow copy
import copy
org = [0, 1, 2, 3, 4], [5, 6, 7, 8, 9]
cpy = copy.copy(org)
cpy[0][1] = -10
print(cpy)
print(org)

([0, -10, 2, 3, 4], [5, 6, 7, 8, 9])
([0, -10, 2, 3, 4], [5, 6, 7, 8, 9])


In [30]:
# deep copy
import copy
org = [0,1,2,3,4],[5,6,7,8,9]
cpy = copy.deepcopy(org)
cpy[0][1] = -10
print(cpy)
print(org)

([0, -10, 2, 3, 4], [5, 6, 7, 8, 9])
([0, 1, 2, 3, 4], [5, 6, 7, 8, 9])


In [31]:
# inheritence
print("inheritence:")
import copy
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
p1 = Person("Alex", 27)
p2 = copy.copy(p1)
p2.age = 28
print(p2.age)
print(p1.age)

inheritence:
28
27


In [32]:
# inheritence with shellow copy
import copy
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
class Company:
    def __init__(self, boss, employee):
        self.boss = boss
        self.employee = employee
p1 = Person("Alex", 55)
p2 = Person("joe", 27)
company = Company(p1, p2)
company_clone = copy.copy(company)
company_clone.boss.age = 56
print(company_clone.boss.age)
print(company_clone.boss.age)

inheritence with shellow copy:
56
56


In [34]:
# inheritence with deep copy
import copy
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
class Company:
    def __init__(self, boss, employee):
        self.boss = boss
        self.employee = employee
p1 = Person("Alex", 55)
p2 = Person("joe", 27)
company = Company(p1, p2)
company_clone = copy.copydeep(company)
company_clone.boss.age = 56
print(company_clone.boss.age)
print(company_clone.boss.age)

AttributeError: module 'copy' has no attribute 'copydeep'

In [35]:
# typical example of context meneger
with open("notes.txt", "w") as file:
    file.write("some todoo...")
file = open("notes.txt", "w")
try:
    file.write("some todoo...")
finally:
    file.close()

In [36]:
# typical example of context meneger
from threading import Lock
lock = Lock()
lock.acquire()
'''....'''
lock.release()
with lock:
    '''....'''

In [37]:
# implemnt a context manager for our own classes
class ManagedFile:
    def __init__(self, filename):
        print("init")
        self.filename = filename
    def __enter__(self):
        print("enter")
        self.file = open(self.filename, "w")
        return self.file
    def __exit__(self, exc_type, exc_value, exc_trackback):
        if self.file:
            self.file.close()
            print("exit")
with ManagedFile("notes.txt") as file:
    print("do some stuff...")
    file.write("some todoo...")

init
enter
do some stuff...
exit


In [38]:
# implemnt a context manager for our own classes
class ManagedFile:
    def __init__(self, filename):
        print("init")
        self.filename = filename
    def __enter__(self):
        print("enter")
        self.file = open(self.filename, "w")
        return self.file
    def __exit__(self, exc_type, exc_value, exc_trackback):
        if self.file:
            self.file.close()
            print("exc", exc_type, exc_value)
            print("exit")
with ManagedFile("notes.txt") as file:
    print("do some stuff...")
    file.write("some todoo...")
    file.somemethod()     
print("counting")

init
enter
do some stuff...
exc <class 'AttributeError'> '_io.TextIOWrapper' object has no attribute 'somemethod'
exit


AttributeError: '_io.TextIOWrapper' object has no attribute 'somemethod'

In [39]:
# implemnt a context manager for our own classes
class ManagedFile:
    def __init__(self, filename):
        print("init")
        self.filename = filename
    def __enter__(self):
        print("enter")
        self.file = open(self.filename, "w")
        return self.file
    def __exit__(self, exc_type, exc_value, exc_trackback):
        if self.file:
            self.file.close()
        if exc_type is not None:
            print("exception has been handle")
        print("exc", exc_type, exc_value)
        print("exit")
        return True
with ManagedFile("notes.txt") as file:
    print("do some stuff...")
    file.write("some todoo...")
    file.somemethod()     
print("counting")

init
enter
do some stuff...
exception has been handle
exc <class 'AttributeError'> '_io.TextIOWrapper' object has no attribute 'somemethod'
exit
counting


In [ ]:
from contextlib import contextmanager
@contextmanager
def open_managed_file(filename):
    f = open(filename, "w")
    try:
        yield f
    finally:
        f.close()
with open_managed_file("notes.txt") as f:
    f.write("some todoo...")