In [1]:
array = [10,20,30]
print(array)
print(array)
array

[10, 20, 30]
[10, 20, 30]


[10, 20, 30]

In [2]:
import numpy as np
myarr = np.array([3,6,32,7])
print(myarr)
myarr

[ 3  6 32  7]


array([ 3,  6, 32,  7])

In [3]:
myarr = np.array([3,6,32,7],np.int8)
print(myarr)
myarr

[ 3  6 32  7]


array([ 3,  6, 32,  7], dtype=int8)

In [4]:
myarr = np.array([3,6,32,7],np.int8)
print([0,1])
print(myarr[0])
myarr

[0, 1]
3


array([ 3,  6, 32,  7], dtype=int8)

In [5]:
myarr = np.array([[3,6,32,7]],np.int8)
print(myarr[0])
print(myarr[0,1])
myarr

[ 3  6 32  7]
6


array([[ 3,  6, 32,  7]], dtype=int8)

In [6]:
myarr = np.array([[3,6,32,7]],np.int8)
print(myarr)
myarr[0,1] = 45
print(myarr)
myarr

[[ 3  6 32  7]]
[[ 3 45 32  7]]


array([[ 3, 45, 32,  7]], dtype=int8)

_array creatino: Conversion from other Python structure_

In [7]:
listarray = np.array([[1,2,3],[4,5,6],[0,3,1]])
print(listarray)
listarray

[[1 2 3]
 [4 5 6]
 [0 3 1]]


array([[1, 2, 3],
       [4, 5, 6],
       [0, 3, 1]])

In [8]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])
listarray.dtype

dtype('int32')

In [9]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])
listarray.shape

(3, 3)

In [10]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])
listarray.size

9

In [11]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [12]:
zeros = np.zeros((2,5))
zeros.dtype

dtype('float64')

In [13]:
zeros = np.zeros((2,5))
zeros.shape

(2, 5)

In [14]:
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
lspace = np.linspace(1,5,12)
print(lspace)
lspace

[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]


array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [17]:
lspace = np.linspace(1,50,10)
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [18]:
lspace = np.linspace(1,4,4)
lspace

array([1., 2., 3., 4.])

In [19]:
lspace = np.linspace(1,5,4)
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [20]:
emp = np.empty((4,6))
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34609111e-307, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.29060531e-306,
        2.13620807e-306, 1.69118787e-306, 2.56765117e-312]])

In [21]:
emp_like = np.empty_like(lspace)
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [22]:
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [23]:
ide = np.identity(45)
ide.shape

(45, 45)

In [24]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [25]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [26]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
arr.shape

(99,)

_numpy axis_

In [28]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [33]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar.sum(axis = 0)

array([12,  8,  9])

In [34]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar.sum(axis=1)

array([ 6, 15,  8])

In [38]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [39]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.flat

In [41]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [42]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.ndim

2

In [43]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
arr.size

99

In [44]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.nbytes

36

In [54]:
one = np.array([1,3,4,634,2])
one.argmax()

3

In [64]:
one = np.array([5,3,1,634,2])
one.argmin()

2

In [65]:
one = np.array([1,3,4,634,2])
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [69]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [70]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [71]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [72]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [74]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [75]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [76]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.reshape(9,)

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [77]:
# add to matrix from difference source
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [78]:
[324,34] + [34,546]

[324, 34, 34, 546]

In [80]:
# matix multipication
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [81]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [84]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.sum()

29

In [85]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar.max()

7

In [86]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [88]:
x = [[1,2,3],[4,0,6],[7,1,0]]
ar = np.array(x)
np.count_nonzero(ar)

7

In [89]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [90]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar[1,2] = 0
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [91]:
import sys
py_ar = [0,4,55,2]
np_ar = np.array(py_ar)
sys.getsizeof(1) * len(py_ar)

112

In [92]:
import sys
py_ar = [0,4,55,2]
np_ar = np.array(py_ar)
np_ar.itemsize * np_ar.size

16

In [93]:
py_ar = [0,4,55,2]
np_ar = np.array(py_ar)
np_ar.tolist()

[0, 4, 55, 2]

In [94]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [95]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [96]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b.ndim

2

In [97]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b.shape

(2, 3)

In [99]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b.dtype

dtype('float64')

In [100]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b.size

6

In [101]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b.size * b.itemsize

48

In [103]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b.nbytes

48

In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b.itemsize

_Accessing/Changing specific elemets, rows, columns, etc_

In [104]:
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [105]:
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x.shape

(2, 7)

In [106]:
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x[1]

array([ 8,  9, 10, 11, 12, 13, 14])

In [107]:
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x[1,5]

13

In [108]:
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [109]:
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x[:,2]

array([ 3, 10])

In [110]:
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x[0,1:6:2]

array([2, 4, 6])

In [112]:
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x[1,5] = 20
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [114]:
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
x[:,2] = 5
print(x)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13 14]]


In [115]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [116]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b[0,1,1]

4

In [117]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [118]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

__initilizing different types of array__

In [119]:
np.zeros((2))

array([0., 0.])

In [123]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [124]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [125]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [129]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [130]:
np.zeros((4,2,2),dtype='int32')

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [132]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [133]:
np.full_like(a,4)

array([4, 4, 4])

In [134]:
np.random.rand(4,2)

array([[0.65674355, 0.81697877],
       [0.30612727, 0.73531759],
       [0.69212218, 0.56604168],
       [0.18885247, 0.88955175]])

In [135]:
np.random.rand(4,2,3)

array([[[0.34879693, 0.54522686, 0.34835099],
        [0.94567424, 0.1746442 , 0.58651572]],

       [[0.82778413, 0.32686248, 0.79996044],
        [0.11338589, 0.3780114 , 0.70080153]],

       [[0.32685124, 0.11953347, 0.79823578],
        [0.11284553, 0.59258992, 0.10282991]],

       [[0.18800706, 0.29840653, 0.82596303],
        [0.7514952 , 0.76655771, 0.87884944]]])

In [138]:
np.random.randint(7)

1

In [139]:
np.random.randint(7,size=(3,3))

array([[5, 2, 6],
       [1, 3, 6],
       [0, 1, 4]])

In [140]:
np.random.randint(4,8,size=(3,3))

array([[4, 4, 4],
       [6, 6, 4],
       [4, 6, 7]])

In [141]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [142]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [143]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [144]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [145]:
z = np.zeros((3,3))
print(z)
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [146]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
print(z)
output[1:4,1:4] = z
print(output)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [147]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
print(z)
output[1:-1,1:-1] = z
print(output)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [148]:
a = np.array([1,2,3])
b = a
b

array([1, 2, 3])

In [149]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)

[100   2   3]


In [150]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)

[100   2   3]


__mathmematics__

In [151]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [152]:
a = np.array([1,2,3,4])
a + 2

array([3, 4, 5, 6])

In [154]:
a = np.array([1,2,3,4])
a - 2

array([-1,  0,  1,  2])

In [155]:
a = np.array([1,2,3,4])
a * 2

array([2, 4, 6, 8])

In [156]:
a = np.array([1,2,3,4])
a / 2

array([0.5, 1. , 1.5, 2. ])

In [157]:
b = np.array([1,0,1,0])
a = np.array([1,2,3,4])
a + b

array([2, 2, 4, 4])

In [158]:
a = np.array([1,2,3,4])
a ** 2

array([ 1,  4,  9, 16])

In [159]:
a = np.array([1,2,3,4])
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [160]:
a = np.array([1,2,3,4])
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

__linear aljebra__

In [161]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [162]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [163]:
c = np.identity(3)
np.linalg.det(c)

1.0

__statistics__

In [164]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [165]:
stats = np.array([[1,2,3],[4,5,6]])
np.min(stats)

1

In [166]:
stats = np.array([[1,2,3],[4,5,6]])
np.max(stats)

6

In [172]:
stats = np.array([[1,2,3],[4,5,6]])
np.min(stats,axis=0)

array([1, 2, 3])

In [173]:
stats = np.array([[1,2,3],[4,5,6]])
np.max(stats,axis=0)

array([4, 5, 6])

In [174]:
stats = np.array([[1,2,3],[4,5,6]])
np.min(stats,axis=1)

array([1, 4])

In [175]:
stats = np.array([[1,2,3],[4,5,6]])
np.max(stats,axis=1)

array([3, 6])

__reogaizing arrays__

In [178]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [179]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [181]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [182]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

__Mesellaneous__

Load Data from File

In [183]:
import numpy as np
np.genfromtxt('data.txt',delimiter=',')

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   5.,
          6.,   7.,   0.,  11.,  12.,   3.,  19.],
       [  1.,  22.,  33.,  11., 999.,  12.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [184]:
import numpy as np
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata.astype('int32')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   5.,
          6.,   7.,   0.,  11.,  12.,   3.,  19.],
       [  1.,  22.,  33.,  11., 999.,  12.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [187]:
import numpy as np
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   5,   6,   7,
          0,  11,  12,   3,  19],
       [  1,  22,  33,  11, 999,  12,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

__Boolean masking and Advanced Indexing__

In [188]:
import numpy as np
before = np.genfromtxt('data.txt',delimiter=',')
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [189]:
import numpy as np
before = np.genfromtxt('data.txt',delimiter=',')
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [190]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [191]:
import numpy as np
before = np.genfromtxt('data.txt',delimiter=',')
np.any(before>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [192]:
before = np.genfromtxt('data.txt',delimiter=',')
np.any(before>50,axis=1)

array([ True,  True,  True])

In [193]:
before = np.genfromtxt('data.txt',delimiter=',')
((before > 50) & (before < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [194]:
import numpy as np
before = np.genfromtxt('data.txt',delimiter=',')
(~((before > 50) & (before < 1000)))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])